# Generated by Django 3.2 on 2021-06-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='librat',
            fields=[
                ('id_libri', models.IntegerField(primary_key=True, serialize=False)),
                ('isbn', models.IntegerField()),
                ('titulli', models.CharField(max_length=500)),
                ('autori', models.CharField(max_length=100)),
                ('kategoria', models.CharField(max_length=100)),
                ('pershkrimi', models.TextField()),
                ('mes_vleresimit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nr_vleresimit', models.IntegerField()),
                ('nr_faqeve', models.IntegerField()),
                ('viti_publikimit', models.IntegerField()),
            ],
        ),
    ]
