# Generated by Django 3.2.4 on 2021-07-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri_im', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_link',
            field=models.CharField(default='', max_length=500),
        ),
    ]
