# Generated by Django 3.2 on 2021-06-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri_im', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librat',
            name='id_libri',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
