# Generated by Django 3.2.4 on 2021-07-23 12:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri_im', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='kategoria',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2000), size=None),
        ),
    ]
