# Generated by Django 3.2.4 on 2021-07-06 09:49

from django.db import migrations, models
import libri_im.models


class Migration(migrations.Migration):

    dependencies = [
        ('libri_im', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='profileImg',
            field=models.ImageField(blank=True, default=libri_im.models.get_default_profile_image, max_length=255, null=True, upload_to=libri_im.models.get_profile_image_filepath),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_link',
            field=models.CharField(default='https://www.directtextbook.com/medium/.jpg', max_length=500),
        ),
    ]
