# Generated by Django 3.2.4 on 2021-07-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri_im', '0002_auto_20210706_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='autori',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='book',
            name='kategoria',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='book',
            name='titulli',
            field=models.CharField(max_length=2000),
        ),
    ]
