# Generated by Django 3.2.4 on 2021-07-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri_im', '0002_book_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_link',
            field=models.CharField(default='https://www.directtextbook.com/large/', max_length=500),
        ),
    ]
