# Generated by Django 3.2.4 on 2021-06-23 08:50

import django.contrib.postgres.fields
from django.db import migrations, models
import libri_im.models


class Migration(migrations.Migration):

    dependencies = [
        ('libri_im', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='newUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default=libri_im.models.get_default_profile_image, max_length=255, null=True, upload_to=libri_im.models.get_profile_image_path)),
                ('hide_email', models.BooleanField(default=True)),
                ('read', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('want_to_read', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('reading', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='librat',
            new_name='Books',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
