# Generated by Django 3.2.4 on 2021-07-12 11:49

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libri_im', '0004_alter_newuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='read',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='reading',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='want_to_read',
        ),
        migrations.CreateModel(
            name='Sirtar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emri', models.CharField(max_length=200)),
                ('books', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None)),
                ('is_public', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
