# Generated by Django 3.2.4 on 2021-07-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri_im', '0004_alter_book_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.BigIntegerField(),
        ),
    ]
