# Generated by Django 3.2.4 on 2021-07-12 11:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri_im', '0005_auto_20210712_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='read',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='newuser',
            name='reading',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='newuser',
            name='want_to_read',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
