# Generated by Django 3.2.4 on 2021-06-23 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libri_im', '0006_auto_20210623_1120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
