# Generated by Django 3.2.4 on 2021-07-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri_im', '0006_auto_20210712_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirtar',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
