# Generated by Django 3.2.4 on 2021-07-12 16:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri_im', '0007_alter_sirtar_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirtar',
            name='books',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
